# Generated by Django 4.2.2 on 2023-06-30 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churras', '0004_prato_foto_prato'),
    ]

    operations = [
       ##### ),
    ]
